### ISSUE TITLE
After updating the kernel to 6.12, dualshock 4 fell off. 

### ISSUE THREAD

**Issue by Rootovich** [ozz-is-here/hid-sony-fix-dkms#1]
After updating the kernel to 6.12, dualshock 4 fell off. 
I tried to reinstall hid-sony-fix-dkms
It gives an error during installation:
```
sudo dkms install -m hid-sony-fix-dkms -v 0.1

Sign command: /lib/modules/6.12.5-6.12-alt2/build/scripts/sign-file
Binary /lib/modules/6.12.5-6.12-alt2/build/scripts/sign-file not found, modules won't be signed

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.12.5-6.12-alt2 KVERSION=6.12.5-6.12-alt2

Error! Bad return status for module build on kernel: 6.12.5-6.12-alt2 (x86_64)
Consult /var/lib/dkms/hid-sony-fix-dkms/0.1/build/make.log for more information.
[thiamine@ALT-Regular-OSIO ~]$ sudo dkms remove -m hid-sony-fix-dkms -v 0.1
Module hid-sony-fix-dkms/0.1 is not installed for kernel 6.12.5-6.12-alt2 (x86_64). Skipping...
Module hid-sony-fix-dkms/0.1 is not built for kernel 6.12.5-6.12-alt2 (x86_64). Skipping...
[thiamine@ALT-Regular-OSIO ~]$ sudo dkms install -m hid-sony-fix-dkms -v 0.1

Sign command: /lib/modules/6.12.5-6.12-alt2/build/scripts/sign-file
Binary /lib/modules/6.12.5-6.12-alt2/build/scripts/sign-file not found, modules won't be signed

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.12.5-6.12-alt2 KVERSION=6.12.5-6.12-alt2

Error! Bad return status for module build on kernel: 6.12.5-6.12-alt2 (x86_64)
Consult /var/lib/dkms/hid-sony-fix-dkms/0.1/build/make.log for more information.
```

There is a build error in the log:

```
DKMS make.log for hid-sony-fix-dkms/0.1 for kernel 6.12.5-6.12-alt2 (x86_64)
Пн 16 дек 2024 15:25:24 MSK
make -C /lib/modules/6.12.5-6.12-alt2/build M=/var/lib/dkms/hid-sony-fix-dkms/0.1/build modules
make[1]: вход в каталог «/usr/src/linux-6.12.5-6.12-alt2»
  CC [M]  /var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.o
/var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.c:43:10: fatal error: asm/unaligned.h: Нет такого файла или каталога
   43 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.o] Error 1
make[2]: *** [/usr/src/linux-6.12.5-6.12-alt2/Makefile:1937: /var/lib/dkms/hid-sony-fix-dkms/0.1/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: выход из каталога «/usr/src/linux-6.12.5-6.12-alt2»
make: *** [Makefile:5: all] Error 2
```
----------------------
On 6.11, the module was installed normally and the controller was working
The problem is on two machines with different hardware

P.S.:  An update is needed
"RC2, released on October 6, 2024, was unusually large for a second release candidate. Key changes included:
  Global Header Renaming: The global header file asm/unaligned.h was renamed to linux/unaligned.h."
https://ostechnix.com/linux-kernel-6-12-released/

**Comment by Rootovich** [comment]
I changed the link, another error came out

--------

```
DKMS make.log for hid-sony-fix-dkms/0.1 for kernel 6.12.5-6.12-alt2 (x86_64)
Вт 17 дек 2024 10:56:59 MSK
make -C /lib/modules/6.12.5-6.12-alt2/build M=/var/lib/dkms/hid-sony-fix-dkms/0.1/build modules
make[1]: вход в каталог «/usr/src/linux-6.12.5-6.12-alt2»
  CC [M]  /var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.o
/var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.c:3257:29: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘u8 * (*)(struct hid_device *, u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
 3257 |         .report_fixup     = sony_report_fixup,
      |                             ^~~~~~~~~~~~~~~~~
/var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.c:3257:29: note: (near initialization for ‘sony_driver.report_fixup’)
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-sony-fix-dkms/0.1/build/hid-sony-fix-dkms.o] Error 1
make[2]: *** [/usr/src/linux-6.12.5-6.12-alt2/Makefile:1937: /var/lib/dkms/hid-sony-fix-dkms/0.1/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: выход из каталога «/usr/src/linux-6.12.5-6.12-alt2»
make: *** [Makefile:5: all] Error 2
```

**Comment by Podberezovik34** [comment]
Did you remember to install kernel-headers-modules-6.12 kernel-headers-6.12 before that? I just had this with another kernel, it turned out I just didn't install these packages. They are not included in the kernel dependencies, so when switching to another branch of the kernel, these packages need to be installed separately.

**Comment by Podberezovik34** [comment]
Hello! Did you manage to run the gamepad on the 6.12 core?

**Comment by Rootovich** [comment]
> Hello! Did you manage to run the gamepad on the 6.12 core?
no, not working in two pc :(
